feat: add force_new_deployment variable
cloudposse/terraform-aws-ecs-web-app pull request #138
Opened 2021-03-31 09:08 UTC by syphernl

## what
* Added the `force_new_deployment` flag to force new task deployment of the service
* Updated github configs

## why
* To make it possible to force a new deployment

## references
* https://github.com/cloudposse/terraform-aws-ecs-alb-service-task/pull/112

2021-04-04 21:49 UTC, Nuru requested changes

2021-04-04 21:49 UTC, Nuru commented on .github/workflows/validate-codeowners.yml
> -
You probably did not mean to delete this, but in any case, the `workflow_dispatch` trigger needs to remain

2021-04-05 04:03 UTC, nitrocode commented
/test all

2021-04-05 04:03 UTC, nitrocode submitted a review, later dismissed

2021-04-05 04:04 UTC, nitrocode commented
/test all

2021-04-05 04:04 UTC, nitrocode approved these changes

2021-04-09 16:53 UTC, Gowiem commented
/test all

2021-04-09 16:53 UTC, Gowiem approved these changes

2021-04-09 19:38 UTC, merged